// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://addmjmsdiqrauebgghni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZG1qbXNkaXFyYXVlYmdnaG5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTM4NjMsImV4cCI6MjA2OTk4OTg2M30.jGC4pqn5f4luoSahUvxkxcUug_74MTijAxaUyAeDVlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});